stevehipwell/helm-charts

- charts/nexus3/Chart.yaml
- charts/nexus3/templates/NOTES.txt
Setting up Nexus3 with an ingress currently fails due to a bug in the
NOTES.txt
> Nexus3: fix ingress settings

- charts/sonarqube/CHANGELOG.md
- charts/sonarqube/Chart.yaml
- charts/sonarqube/templates/_helpers.tpl
- charts/sonarqube/templates/deployment.yaml
Fixes https://github.com/stevehipwell/helm-charts/issues/136.
> [sonarqube] Fix postgresql support

- charts/istio-operator/CHANGELOG.md
- charts/istio-operator/Chart.yaml
- charts/istio-operator/templates/clusterrole.yaml
This PR upgrades the istio version to 1.9.1
> [istio-operator] Upgrade istio to v1.9.1

- charts/metrics-server/CHANGELOG.md
- charts/metrics-server/Chart.yaml
- charts/metrics-server/README.md
- charts/metrics-server/templates/deployment.yaml
- charts/metrics-server/values.yaml
> [metrics-server] Add additional volume support

- charts/plantuml/CHANGELOG.md
- charts/plantuml/Chart.yaml
- charts/plantuml/templates/NOTES.txt
- charts/plantuml/templates/ingress.yaml
> [plantuml] Fix ingress

- charts/jira-software/CHANGELOG.md
- charts/jira-software/Chart.yaml
- charts/jira-software/templates/ingress.yaml
> [jira-software] Fix ingress

- charts/istio-operator/CHANGELOG.md
- charts/istio-operator/Chart.yaml
- charts/istio-operator/templates/clusterrole.yaml
Address issue  #359 by adding `pods/portforward` permissions to the Istio Operator's `ClusterRole`.
> [istio-operator] Added pods/portforward to operator ClusterRole

- charts/plantuml/CHANGELOG.md
- charts/plantuml/Chart.yaml
- charts/plantuml/README.md
- charts/plantuml/_release-notes.md
- charts/plantuml/templates/deployment.yaml
- charts/plantuml/values.yaml
> [plantuml] Add support for args

- .github/workflows/lint-test.yaml
- .github/workflows/release.yaml
- charts/nexus3/CHANGELOG.md
- charts/nexus3/Chart.yaml
- charts/nexus3/_release-notes.md
- charts/nexus3/files/configure.sh
- charts/nexus3/templates/configmap-config.yaml
As well as updating Nexus3 this PR fixes a hardcoded file path breaking the creation of users, including the anonymous user, and it fixes a bug which would stop the creation of users if more than one was defined.
Closes #436.
> [nexus3] Update image to v3.38.1

- charts/nexus3/CHANGELOG.md
- charts/nexus3/Chart.yaml
- charts/nexus3/_release-notes.md
- charts/nexus3/files/configure.sh
> [nexus3] Fix S3 blob store type lookup

- charts/confluence-server/CHANGELOG.md
- charts/confluence-server/Chart.yaml
- charts/confluence-server/_release-notes.md
- charts/confluence-server/templates/deployment.yaml
> [confluence-server] Update image to v7.17.3

- charts/nexus3/CHANGELOG.md
- charts/nexus3/Chart.yaml
- charts/nexus3/_release-notes.md
- charts/nexus3/templates/statefulset.yaml
> [nexus3] Updated image to v3.42.0

- charts/thanos/CHANGELOG.md
- charts/thanos/Chart.yaml
- charts/thanos/templates/_helpers.tpl
- charts/thanos/templates/query-frontend/hpa.yaml
- charts/thanos/templates/query/hpa.yaml
> feat[thanos]: Updated HPA version

- charts/thanos/CHANGELOG.md
- charts/thanos/Chart.yaml
- charts/thanos/_release-notes.md
- charts/thanos/templates/_helpers.tpl
> fix[thanos]: Fixed API version bug

- charts/plantuml/CHANGELOG.md
- charts/plantuml/Chart.yaml
- charts/plantuml/README.md
- charts/plantuml/templates/deployment.yaml
- charts/plantuml/values.yaml
> feat[plantuml]: Changed security context

- .github/workflows/pull-request.yaml
- charts/plantuml/CHANGELOG.md
- charts/plantuml/Chart.yaml
- charts/plantuml/README.md
- charts/plantuml/templates/deployment.yaml
- charts/plantuml/values.yaml
@grieshaber this should fix the issue you found with the last release. Thanks for pointing this out as it showed me that the tooling wasn't configured correctly which is how it got through.
> fix[plantuml]: Fixed security context bug

- charts/istio-operator/CHANGELOG.md
- charts/istio-operator/templates/istiooperator.yaml
- charts/istio-operator/values.yaml
I'm using ArgoCD to deploy this operator. I need to add an annotation to the CR to the istio-operator chart to handle some lifecycle hooks better.
> Annotations on IstioOperator CR

- charts/nexus3/CHANGELOG.md
- charts/nexus3/Chart.yaml
> feat[nexus3]: Updated image to v3.47.1

- charts/thanos/CHANGELOG.md
- charts/thanos/Chart.yaml
- charts/thanos/templates/receive-ingestor/_helpers.tpl
- charts/thanos/templates/receive-router/_helpers.tpl
- charts/thanos/templates/receive-router/configmap-hashrings.yaml
- charts/thanos/templates/receive-router/deployment.yaml
> feat(thanos): Fixed Receive

- charts/plantuml/CHANGELOG.md
- charts/plantuml/Chart.yaml
- charts/plantuml/ci/kubeconform.yaml
- charts/plantuml/templates/_helpers.tpl
- charts/plantuml/templates/pdb.yaml
> fix(plantuml): Fixed incorrect PDB API

- charts/thanos/CHANGELOG.md
- charts/thanos/Chart.yaml
- charts/thanos/ci/kubeconform.yaml
- charts/thanos/templates/compact/statefulset.yaml
> fix(thanos): Fixed compact deduplication

- .github/workflows/validate-pr.yaml
- charts/confluence-server/CHANGELOG.md
- charts/confluence-server/Chart.yaml
- charts/confluence-server/templates/_helpers.tpl
> feat(confluence-server): Fixed incorrect PostgreSQL templates

- charts/nexus3/CHANGELOG.md
- charts/nexus3/Chart.yaml
- charts/nexus3/files/configure.sh
I was chasing down some errors in my configuration. I thought this could help ease the task the next time I mess up my config.
> feat(nexus3): use termination log to record lifecycle errors

- charts/thanos/CHANGELOG.md
- charts/thanos/Chart.yaml
- charts/thanos/README.md
- charts/thanos/ci/kubeconform.yaml
- charts/thanos/templates/compact/statefulset.yaml
- charts/thanos/templates/query-frontend/deployment.yaml
- charts/thanos/templates/query/deployment.yaml
- charts/thanos/templates/receive-ingestor/statefulset.yaml
- charts/thanos/templates/receive-router/deployment.yaml
- charts/thanos/templates/rule/statefulset.yaml
- charts/thanos/templates/store-gateway/statefulset.yaml
- charts/thanos/values.yaml
> feat(thanos): Added support for extra volumes

- charts/nexus3/CHANGELOG.md
- charts/nexus3/values.yaml
> fix(nexus3): Fixed root password logic

- .github/workflows/release.yaml
- .github/workflows/validate-pr.yaml
- charts/thanos/CHANGELOG.md
- charts/thanos/Chart.yaml
- charts/thanos/README.md
- charts/thanos/templates/query-frontend/ingress.yaml
- charts/thanos/templates/query/ingress.yaml
- charts/thanos/templates/receive-router/ingress.yaml
- charts/thanos/templates/rule/ingress.yaml
> feat(thanos): Added remote write ingress support to receive

- charts/tigera-operator/CHANGELOG.md
- charts/tigera-operator/Chart.yaml
- charts/tigera-operator/README.md
- charts/tigera-operator/templates/clusterrole.yaml
> fix(tigera-operator): Fixed role for ippools

- charts/nexus3/CHANGELOG.md
- charts/nexus3/Chart.yaml
- charts/nexus3/README.md
- charts/nexus3/ci/ci-values.yaml
- charts/nexus3/ci/kubeconform.yaml
- charts/nexus3/scripts/configure.sh
- charts/nexus3/templates/_test/secret-test-password.yaml
- charts/nexus3/templates/configmap-config.yaml
- charts/nexus3/templates/job-config.yaml
- charts/nexus3/values.yaml
> feat: Added repo & user password support

- charts/fluent-bit-aggregator/CHANGELOG.md
- charts/fluent-bit-aggregator/Chart.yaml
- charts/fluent-bit-aggregator/README.md
- charts/fluent-bit-aggregator/values.yaml
- charts/fluent-bit-collector/CHANGELOG.md
- charts/fluent-bit-collector/Chart.yaml
- charts/fluent-bit-collector/README.md
- charts/fluent-bit-collector/values.yaml
- charts/nexus3/CHANGELOG.md
- charts/nexus3/Chart.yaml
- charts/nexus3/README.md
- charts/nexus3/values.yaml
- charts/thanos/CHANGELOG.md
- charts/thanos/Chart.yaml
- charts/thanos/README.md
- charts/thanos/values.yaml
> fix: Fixed errors caused by the removal of free Chainguard images

- charts/nexus3/CHANGELOG.md
- charts/nexus3/Chart.yaml
- charts/nexus3/README.md
- charts/nexus3/ci/ci-values.yaml
- charts/nexus3/scripts/configure.sh
> fix(nexus3): Fixed user config

- charts/vertical-pod-autoscaler/CHANGELOG.md
- charts/vertical-pod-autoscaler/Chart.yaml
- charts/vertical-pod-autoscaler/README.md
- charts/vertical-pod-autoscaler/crds/verticalpodautoscalercheckpoints.autoscaling.k8s.io.yaml
- charts/vertical-pod-autoscaler/crds/verticalpodautoscalers.autoscaling.k8s.io.yaml
- charts/vertical-pod-autoscaler/templates/rbac.yaml
- charts/vertical-pod-autoscaler/templates/recommender/deployment.yaml
- charts/vertical-pod-autoscaler/templates/updater/deployment.yaml
- charts/vertical-pod-autoscaler/values.yaml
> feat(vpa): Updated image to v1.3.0

- charts/nexus3/CHANGELOG.md
- charts/nexus3/templates/configmap-logback.yaml
> fix(nexus3): Fix tasks logback config

- charts/nexus3/CHANGELOG.md
- charts/nexus3/Chart.yaml
- charts/nexus3/README.md
- charts/nexus3/ci/kubeconform.yaml
- charts/nexus3/scripts/configure.sh
- charts/nexus3/templates/configmap-config.yaml
- charts/nexus3/templates/job-config.yaml
- charts/nexus3/values.yaml
> feat(nexus3): Update image to v3.81.1

- charts/vertical-pod-autoscaler/CHANGELOG.md
- charts/vertical-pod-autoscaler/Chart.yaml
- charts/vertical-pod-autoscaler/README.md
- charts/vertical-pod-autoscaler/crds/verticalpodautoscalers.autoscaling.k8s.io.yaml
> fix(vpa): correct crd typo

- charts/thanos/CHANGELOG.md
- charts/thanos/README.md
- charts/thanos/values.yaml
> fix(thanos): Remove reference to unused existing claims from persistence

- charts/thanos/CHANGELOG.md
- charts/thanos/README.md
- charts/thanos/templates/compact/statefulset.yaml
- charts/thanos/templates/query-frontend/deployment.yaml
- charts/thanos/templates/query/deployment.yaml
- charts/thanos/templates/receive-ingestor/statefulset.yaml
- charts/thanos/templates/receive-router/deployment.yaml
- charts/thanos/templates/rule/statefulset.yaml
- charts/thanos/templates/store-gateway/statefulset.yaml
- charts/thanos/values.yaml
This PR adds support for templating additional endpoints and endpoint groups.
Closes #1258
> feat(thanos): Add tpl support for endpoints
